// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CallCreateNewEndpoint(arg1:model.NewEndpoint):Promise<string>;

export function CallLoadEndpoints():Promise<model.EndpointStore>;
